// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: examenes.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getExamenByID = `-- name: GetExamenByID :one
SELECT id, titulo, codigo_cuadernillo, descripcion, nivel, tipo, anio, total_preguntas, duracion_minutos
FROM examenes
WHERE id = $1 AND activo = true
LIMIT 1
`

type GetExamenByIDRow struct {
	ID                pgtype.UUID `json:"id"`
	Titulo            string      `json:"titulo"`
	CodigoCuadernillo string      `json:"codigo_cuadernillo"`
	Descripcion       pgtype.Text `json:"descripcion"`
	Nivel             string      `json:"nivel"`
	Tipo              string      `json:"tipo"`
	Anio              int32       `json:"anio"`
	TotalPreguntas    int32       `json:"total_preguntas"`
	DuracionMinutos   int32       `json:"duracion_minutos"`
}

func (q *Queries) GetExamenByID(ctx context.Context, id pgtype.UUID) (GetExamenByIDRow, error) {
	row := q.db.QueryRow(ctx, getExamenByID, id)
	var i GetExamenByIDRow
	err := row.Scan(
		&i.ID,
		&i.Titulo,
		&i.CodigoCuadernillo,
		&i.Descripcion,
		&i.Nivel,
		&i.Tipo,
		&i.Anio,
		&i.TotalPreguntas,
		&i.DuracionMinutos,
	)
	return i, err
}

const getOpcionesByPreguntaIDs = `-- name: GetOpcionesByPreguntaIDs :many
SELECT id, pregunta_id, etiqueta, texto_opcion, es_correcta
FROM opciones
WHERE pregunta_id = ANY($1::uuid[])
ORDER BY etiqueta ASC
`

func (q *Queries) GetOpcionesByPreguntaIDs(ctx context.Context, dollar_1 []pgtype.UUID) ([]Opcione, error) {
	rows, err := q.db.Query(ctx, getOpcionesByPreguntaIDs, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Opcione{}
	for rows.Next() {
		var i Opcione
		if err := rows.Scan(
			&i.ID,
			&i.PreguntaID,
			&i.Etiqueta,
			&i.TextoOpcion,
			&i.EsCorrecta,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPreguntasByExamenID = `-- name: GetPreguntasByExamenID :many
SELECT id, examen_id, texto_base_id, numero_pregunta, texto_pregunta, url_imagen, explicacion
FROM preguntas
WHERE examen_id = $1
ORDER BY numero_pregunta ASC
`

type GetPreguntasByExamenIDRow struct {
	ID             pgtype.UUID `json:"id"`
	ExamenID       pgtype.UUID `json:"examen_id"`
	TextoBaseID    pgtype.UUID `json:"texto_base_id"`
	NumeroPregunta int32       `json:"numero_pregunta"`
	TextoPregunta  string      `json:"texto_pregunta"`
	UrlImagen      pgtype.Text `json:"url_imagen"`
	Explicacion    pgtype.Text `json:"explicacion"`
}

func (q *Queries) GetPreguntasByExamenID(ctx context.Context, examenID pgtype.UUID) ([]GetPreguntasByExamenIDRow, error) {
	rows, err := q.db.Query(ctx, getPreguntasByExamenID, examenID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetPreguntasByExamenIDRow{}
	for rows.Next() {
		var i GetPreguntasByExamenIDRow
		if err := rows.Scan(
			&i.ID,
			&i.ExamenID,
			&i.TextoBaseID,
			&i.NumeroPregunta,
			&i.TextoPregunta,
			&i.UrlImagen,
			&i.Explicacion,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTextosBaseByExamenID = `-- name: GetTextosBaseByExamenID :many
SELECT id, examen_id, codigo_texto_base, titulo, contenido
FROM textos_base
WHERE examen_id = $1
ORDER BY codigo_texto_base ASC
`

type GetTextosBaseByExamenIDRow struct {
	ID              pgtype.UUID `json:"id"`
	ExamenID        pgtype.UUID `json:"examen_id"`
	CodigoTextoBase string      `json:"codigo_texto_base"`
	Titulo          pgtype.Text `json:"titulo"`
	Contenido       string      `json:"contenido"`
}

func (q *Queries) GetTextosBaseByExamenID(ctx context.Context, examenID pgtype.UUID) ([]GetTextosBaseByExamenIDRow, error) {
	rows, err := q.db.Query(ctx, getTextosBaseByExamenID, examenID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetTextosBaseByExamenIDRow{}
	for rows.Next() {
		var i GetTextosBaseByExamenIDRow
		if err := rows.Scan(
			&i.ID,
			&i.ExamenID,
			&i.CodigoTextoBase,
			&i.Titulo,
			&i.Contenido,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listExamenesActivos = `-- name: ListExamenesActivos :many
SELECT id, titulo, codigo_cuadernillo, descripcion, nivel, tipo, anio, total_preguntas, duracion_minutos
FROM examenes
WHERE activo = true
ORDER BY anio DESC, titulo ASC
`

type ListExamenesActivosRow struct {
	ID                pgtype.UUID `json:"id"`
	Titulo            string      `json:"titulo"`
	CodigoCuadernillo string      `json:"codigo_cuadernillo"`
	Descripcion       pgtype.Text `json:"descripcion"`
	Nivel             string      `json:"nivel"`
	Tipo              string      `json:"tipo"`
	Anio              int32       `json:"anio"`
	TotalPreguntas    int32       `json:"total_preguntas"`
	DuracionMinutos   int32       `json:"duracion_minutos"`
}

func (q *Queries) ListExamenesActivos(ctx context.Context) ([]ListExamenesActivosRow, error) {
	rows, err := q.db.Query(ctx, listExamenesActivos)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListExamenesActivosRow{}
	for rows.Next() {
		var i ListExamenesActivosRow
		if err := rows.Scan(
			&i.ID,
			&i.Titulo,
			&i.CodigoCuadernillo,
			&i.Descripcion,
			&i.Nivel,
			&i.Tipo,
			&i.Anio,
			&i.TotalPreguntas,
			&i.DuracionMinutos,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
