// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: intentos.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const finalizarIntento = `-- name: FinalizarIntento :exec
UPDATE intentos_examen
SET 
    puntaje = $2,
    preguntas_correctas = $3,
    preguntas_incorrectas = $4,
    estado = 'completado',
    finalizado_en = NOW()
WHERE id = $1 AND usuario_id = $5
`

type FinalizarIntentoParams struct {
	ID                   pgtype.UUID    `json:"id"`
	Puntaje              pgtype.Numeric `json:"puntaje"`
	PreguntasCorrectas   int32          `json:"preguntas_correctas"`
	PreguntasIncorrectas int32          `json:"preguntas_incorrectas"`
	UsuarioID            pgtype.UUID    `json:"usuario_id"`
}

func (q *Queries) FinalizarIntento(ctx context.Context, arg FinalizarIntentoParams) error {
	_, err := q.db.Exec(ctx, finalizarIntento,
		arg.ID,
		arg.Puntaje,
		arg.PreguntasCorrectas,
		arg.PreguntasIncorrectas,
		arg.UsuarioID,
	)
	return err
}

const getClavesYExplicacionesByExamenID = `-- name: GetClavesYExplicacionesByExamenID :many
SELECT 
    p.id AS pregunta_id,
    p.numero_pregunta,
    COALESCE(o.id, '00000000-0000-0000-0000-000000000000'::uuid) AS opcion_correcta_id,
    p.explicacion
FROM preguntas p
LEFT JOIN opciones o ON o.pregunta_id = p.id AND o.es_correcta = TRUE
WHERE p.examen_id = $1
`

type GetClavesYExplicacionesByExamenIDRow struct {
	PreguntaID       pgtype.UUID `json:"pregunta_id"`
	NumeroPregunta   int32       `json:"numero_pregunta"`
	OpcionCorrectaID pgtype.UUID `json:"opcion_correcta_id"`
	Explicacion      pgtype.Text `json:"explicacion"`
}

func (q *Queries) GetClavesYExplicacionesByExamenID(ctx context.Context, examenID pgtype.UUID) ([]GetClavesYExplicacionesByExamenIDRow, error) {
	rows, err := q.db.Query(ctx, getClavesYExplicacionesByExamenID, examenID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetClavesYExplicacionesByExamenIDRow{}
	for rows.Next() {
		var i GetClavesYExplicacionesByExamenIDRow
		if err := rows.Scan(
			&i.PreguntaID,
			&i.NumeroPregunta,
			&i.OpcionCorrectaID,
			&i.Explicacion,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRespuestasPorIntentoID = `-- name: GetRespuestasPorIntentoID :many
SELECT 
    pregunta_id,
    opcion_seleccionada_id,
    es_correcta
FROM respuestas_intento
WHERE intento_id = $1
`

type GetRespuestasPorIntentoIDRow struct {
	PreguntaID           pgtype.UUID `json:"pregunta_id"`
	OpcionSeleccionadaID pgtype.UUID `json:"opcion_seleccionada_id"`
	EsCorrecta           bool        `json:"es_correcta"`
}

func (q *Queries) GetRespuestasPorIntentoID(ctx context.Context, intentoID pgtype.UUID) ([]GetRespuestasPorIntentoIDRow, error) {
	rows, err := q.db.Query(ctx, getRespuestasPorIntentoID, intentoID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetRespuestasPorIntentoIDRow{}
	for rows.Next() {
		var i GetRespuestasPorIntentoIDRow
		if err := rows.Scan(&i.PreguntaID, &i.OpcionSeleccionadaID, &i.EsCorrecta); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const iniciarIntento = `-- name: IniciarIntento :one
INSERT INTO intentos_examen (
    usuario_id,
    examen_id,
    modo,
    total_preguntas,
    estado
) VALUES (
    $1, $2, $3, $4, 'en_progreso'
)
RETURNING id, examen_id, modo, total_preguntas, estado, iniciado_en
`

type IniciarIntentoParams struct {
	UsuarioID      pgtype.UUID `json:"usuario_id"`
	ExamenID       pgtype.UUID `json:"examen_id"`
	Modo           string      `json:"modo"`
	TotalPreguntas int32       `json:"total_preguntas"`
}

type IniciarIntentoRow struct {
	ID             pgtype.UUID        `json:"id"`
	ExamenID       pgtype.UUID        `json:"examen_id"`
	Modo           string             `json:"modo"`
	TotalPreguntas int32              `json:"total_preguntas"`
	Estado         string             `json:"estado"`
	IniciadoEn     pgtype.Timestamptz `json:"iniciado_en"`
}

func (q *Queries) IniciarIntento(ctx context.Context, arg IniciarIntentoParams) (IniciarIntentoRow, error) {
	row := q.db.QueryRow(ctx, iniciarIntento,
		arg.UsuarioID,
		arg.ExamenID,
		arg.Modo,
		arg.TotalPreguntas,
	)
	var i IniciarIntentoRow
	err := row.Scan(
		&i.ID,
		&i.ExamenID,
		&i.Modo,
		&i.TotalPreguntas,
		&i.Estado,
		&i.IniciadoEn,
	)
	return i, err
}

const listarIntentosPorUsuario = `-- name: ListarIntentosPorUsuario :many
SELECT 
    i.id,
    i.examen_id,
    e.titulo AS examen_titulo,
    e.nivel,
    e.tipo,
    e.anio,
    i.modo,
    i.puntaje,
    i.total_preguntas,
    i.preguntas_correctas,
    i.preguntas_incorrectas,
    i.estado,
    i.iniciado_en,
    i.finalizado_en
FROM intentos_examen i
JOIN examenes e ON i.examen_id = e.id
WHERE i.usuario_id = $1
ORDER BY i.iniciado_en DESC
`

type ListarIntentosPorUsuarioRow struct {
	ID                   pgtype.UUID        `json:"id"`
	ExamenID             pgtype.UUID        `json:"examen_id"`
	ExamenTitulo         string             `json:"examen_titulo"`
	Nivel                string             `json:"nivel"`
	Tipo                 string             `json:"tipo"`
	Anio                 int32              `json:"anio"`
	Modo                 string             `json:"modo"`
	Puntaje              pgtype.Numeric     `json:"puntaje"`
	TotalPreguntas       int32              `json:"total_preguntas"`
	PreguntasCorrectas   int32              `json:"preguntas_correctas"`
	PreguntasIncorrectas int32              `json:"preguntas_incorrectas"`
	Estado               string             `json:"estado"`
	IniciadoEn           pgtype.Timestamptz `json:"iniciado_en"`
	FinalizadoEn         pgtype.Timestamptz `json:"finalizado_en"`
}

func (q *Queries) ListarIntentosPorUsuario(ctx context.Context, usuarioID pgtype.UUID) ([]ListarIntentosPorUsuarioRow, error) {
	rows, err := q.db.Query(ctx, listarIntentosPorUsuario, usuarioID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListarIntentosPorUsuarioRow{}
	for rows.Next() {
		var i ListarIntentosPorUsuarioRow
		if err := rows.Scan(
			&i.ID,
			&i.ExamenID,
			&i.ExamenTitulo,
			&i.Nivel,
			&i.Tipo,
			&i.Anio,
			&i.Modo,
			&i.Puntaje,
			&i.TotalPreguntas,
			&i.PreguntasCorrectas,
			&i.PreguntasIncorrectas,
			&i.Estado,
			&i.IniciadoEn,
			&i.FinalizadoEn,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const obtenerIntentoPorID = `-- name: ObtenerIntentoPorID :one
SELECT 
    i.id,
    i.examen_id,
    e.titulo AS examen_titulo,
    i.modo,
    i.puntaje,
    i.total_preguntas,
    i.preguntas_correctas,
    i.preguntas_incorrectas,
    i.estado,
    i.iniciado_en,
    i.finalizado_en
FROM intentos_examen i
JOIN examenes e ON i.examen_id = e.id
WHERE i.id = $1 AND i.usuario_id = $2
`

type ObtenerIntentoPorIDParams struct {
	ID        pgtype.UUID `json:"id"`
	UsuarioID pgtype.UUID `json:"usuario_id"`
}

type ObtenerIntentoPorIDRow struct {
	ID                   pgtype.UUID        `json:"id"`
	ExamenID             pgtype.UUID        `json:"examen_id"`
	ExamenTitulo         string             `json:"examen_titulo"`
	Modo                 string             `json:"modo"`
	Puntaje              pgtype.Numeric     `json:"puntaje"`
	TotalPreguntas       int32              `json:"total_preguntas"`
	PreguntasCorrectas   int32              `json:"preguntas_correctas"`
	PreguntasIncorrectas int32              `json:"preguntas_incorrectas"`
	Estado               string             `json:"estado"`
	IniciadoEn           pgtype.Timestamptz `json:"iniciado_en"`
	FinalizadoEn         pgtype.Timestamptz `json:"finalizado_en"`
}

func (q *Queries) ObtenerIntentoPorID(ctx context.Context, arg ObtenerIntentoPorIDParams) (ObtenerIntentoPorIDRow, error) {
	row := q.db.QueryRow(ctx, obtenerIntentoPorID, arg.ID, arg.UsuarioID)
	var i ObtenerIntentoPorIDRow
	err := row.Scan(
		&i.ID,
		&i.ExamenID,
		&i.ExamenTitulo,
		&i.Modo,
		&i.Puntaje,
		&i.TotalPreguntas,
		&i.PreguntasCorrectas,
		&i.PreguntasIncorrectas,
		&i.Estado,
		&i.IniciadoEn,
		&i.FinalizadoEn,
	)
	return i, err
}

const registrarRespuestaIntento = `-- name: RegistrarRespuestaIntento :exec
INSERT INTO respuestas_intento (
    intento_id,
    pregunta_id,
    opcion_seleccionada_id,
    es_correcta
) VALUES (
    $1, $2, $3, $4
)
ON CONFLICT (intento_id, pregunta_id) 
DO UPDATE SET 
    opcion_seleccionada_id = EXCLUDED.opcion_seleccionada_id,
    es_correcta = EXCLUDED.es_correcta
`

type RegistrarRespuestaIntentoParams struct {
	IntentoID            pgtype.UUID `json:"intento_id"`
	PreguntaID           pgtype.UUID `json:"pregunta_id"`
	OpcionSeleccionadaID pgtype.UUID `json:"opcion_seleccionada_id"`
	EsCorrecta           bool        `json:"es_correcta"`
}

func (q *Queries) RegistrarRespuestaIntento(ctx context.Context, arg RegistrarRespuestaIntentoParams) error {
	_, err := q.db.Exec(ctx, registrarRespuestaIntento,
		arg.IntentoID,
		arg.PreguntaID,
		arg.OpcionSeleccionadaID,
		arg.EsCorrecta,
	)
	return err
}
