// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Examene struct {
	ID                pgtype.UUID        `json:"id"`
	Titulo            string             `json:"titulo"`
	CodigoCuadernillo string             `json:"codigo_cuadernillo"`
	Descripcion       pgtype.Text        `json:"descripcion"`
	Nivel             string             `json:"nivel"`
	Tipo              string             `json:"tipo"`
	Anio              int32              `json:"anio"`
	TotalPreguntas    int32              `json:"total_preguntas"`
	DuracionMinutos   int32              `json:"duracion_minutos"`
	Activo            pgtype.Bool        `json:"activo"`
	CreadoEn          pgtype.Timestamptz `json:"creado_en"`
}

type Intento struct {
	ID                   pgtype.UUID        `json:"id"`
	UsuarioID            pgtype.UUID        `json:"usuario_id"`
	ExamenID             pgtype.UUID        `json:"examen_id"`
	Modo                 string             `json:"modo"`
	Puntaje              pgtype.Numeric     `json:"puntaje"`
	TotalPreguntas       int32              `json:"total_preguntas"`
	PreguntasCorrectas   pgtype.Int4        `json:"preguntas_correctas"`
	PreguntasIncorrectas pgtype.Int4        `json:"preguntas_incorrectas"`
	Estado               pgtype.Text        `json:"estado"`
	IniciadoEn           pgtype.Timestamptz `json:"iniciado_en"`
	FinalizadoEn         pgtype.Timestamptz `json:"finalizado_en"`
}

type IntentoRespuesta struct {
	ID                   pgtype.UUID        `json:"id"`
	IntentoID            pgtype.UUID        `json:"intento_id"`
	PreguntaID           pgtype.UUID        `json:"pregunta_id"`
	OpcionSeleccionadaID pgtype.UUID        `json:"opcion_seleccionada_id"`
	EsCorrecta           bool               `json:"es_correcta"`
	RespondidoEn         pgtype.Timestamptz `json:"respondido_en"`
}

type Opcione struct {
	ID          pgtype.UUID `json:"id"`
	PreguntaID  pgtype.UUID `json:"pregunta_id"`
	Etiqueta    string      `json:"etiqueta"`
	TextoOpcion string      `json:"texto_opcion"`
	EsCorrecta  bool        `json:"es_correcta"`
}

type Pregunta struct {
	ID             pgtype.UUID        `json:"id"`
	ExamenID       pgtype.UUID        `json:"examen_id"`
	NumeroPregunta int32              `json:"numero_pregunta"`
	TextoPregunta  string             `json:"texto_pregunta"`
	UrlImagen      pgtype.Text        `json:"url_imagen"`
	Explicacion    pgtype.Text        `json:"explicacion"`
	CreadoEn       pgtype.Timestamptz `json:"creado_en"`
}

type Usuario struct {
	ID               pgtype.UUID        `json:"id"`
	Correo           string             `json:"correo"`
	ContrasenaHash   string             `json:"contrasena_hash"`
	NombreCompleto   string             `json:"nombre_completo"`
	Rol              pgtype.Text        `json:"rol"`
	SuscripcionHasta pgtype.Timestamptz `json:"suscripcion_hasta"`
	CreadoEn         pgtype.Timestamptz `json:"creado_en"`
	ActualizadoEn    pgtype.Timestamptz `json:"actualizado_en"`
}
