// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"
)

type Querier interface {
	CrearUsuario(ctx context.Context, arg CrearUsuarioParams) (CrearUsuarioRow, error)
	ObtenerUsuarioPorCorreo(ctx context.Context, correo string) (Usuario, error)
}

var _ Querier = (*Queries)(nil)
