// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: suscripciones.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const activarSuscripcion = `-- name: ActivarSuscripcion :one
INSERT INTO suscripciones (
    usuario_id, plan, monto, metodo_pago, numero_operacion, fecha_expiracion
) VALUES (
    $1, $2, $3, $4, $5, $6
) RETURNING id, estado, fecha_inicio, fecha_expiracion
`

type ActivarSuscripcionParams struct {
	UsuarioID       pgtype.UUID        `json:"usuario_id"`
	Plan            TipoPlan           `json:"plan"`
	Monto           pgtype.Numeric     `json:"monto"`
	MetodoPago      pgtype.Text        `json:"metodo_pago"`
	NumeroOperacion pgtype.Text        `json:"numero_operacion"`
	FechaExpiracion pgtype.Timestamptz `json:"fecha_expiracion"`
}

type ActivarSuscripcionRow struct {
	ID              pgtype.UUID           `json:"id"`
	Estado          NullEstadoSuscripcion `json:"estado"`
	FechaInicio     pgtype.Timestamptz    `json:"fecha_inicio"`
	FechaExpiracion pgtype.Timestamptz    `json:"fecha_expiracion"`
}

func (q *Queries) ActivarSuscripcion(ctx context.Context, arg ActivarSuscripcionParams) (ActivarSuscripcionRow, error) {
	row := q.db.QueryRow(ctx, activarSuscripcion,
		arg.UsuarioID,
		arg.Plan,
		arg.Monto,
		arg.MetodoPago,
		arg.NumeroOperacion,
		arg.FechaExpiracion,
	)
	var i ActivarSuscripcionRow
	err := row.Scan(
		&i.ID,
		&i.Estado,
		&i.FechaInicio,
		&i.FechaExpiracion,
	)
	return i, err
}

const checkActiveSubscription = `-- name: CheckActiveSubscription :one
SELECT count(*) > 0 AS has_active_subscription
FROM suscripciones 
WHERE usuario_id = $1 
  AND estado = 'activa' 
  AND fecha_expiracion > NOW()
`

func (q *Queries) CheckActiveSubscription(ctx context.Context, usuarioID pgtype.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, checkActiveSubscription, usuarioID)
	var has_active_subscription bool
	err := row.Scan(&has_active_subscription)
	return has_active_subscription, err
}

const getSuscripcionActiva = `-- name: GetSuscripcionActiva :one
SELECT id, plan, estado, fecha_inicio, fecha_expiracion
FROM suscripciones
WHERE usuario_id = $1 
  AND estado = 'activa' 
  AND fecha_expiracion > NOW()
ORDER BY fecha_expiracion DESC
LIMIT 1
`

type GetSuscripcionActivaRow struct {
	ID              pgtype.UUID           `json:"id"`
	Plan            TipoPlan              `json:"plan"`
	Estado          NullEstadoSuscripcion `json:"estado"`
	FechaInicio     pgtype.Timestamptz    `json:"fecha_inicio"`
	FechaExpiracion pgtype.Timestamptz    `json:"fecha_expiracion"`
}

func (q *Queries) GetSuscripcionActiva(ctx context.Context, usuarioID pgtype.UUID) (GetSuscripcionActivaRow, error) {
	row := q.db.QueryRow(ctx, getSuscripcionActiva, usuarioID)
	var i GetSuscripcionActivaRow
	err := row.Scan(
		&i.ID,
		&i.Plan,
		&i.Estado,
		&i.FechaInicio,
		&i.FechaExpiracion,
	)
	return i, err
}
